In [1]:
# Import packages
import pandas as pd
import numpy as np
import datetime
from collections import defaultdict
import nltk
import random

In [3]:
stemmer = nltk.stem.snowball.SnowballStemmer("english")
data_dir = "/Users/yangsong/Desktop/Projects/gitrepo_songyang0716/Topic_Modeling/reviews_small.txt"
np.random.seed(666)

# read review texts
reviews = []
f = open(data_dir, "r")
for review in f:
    reviews.append(review)
random.shuffle(reviews)

In [4]:
# process text
# tokenize, lower, remove stop words, stem, then only keep alphabets in the string
clean_reviews = []
for review in reviews:
    s = nltk.word_tokenize(review)
    s = [word.lower() for word in s]
    s = [word for word in s if not word in set(
        nltk.corpus.stopwords.words('english'))]
    s = [stemmer.stem(word) for word in s if word.isalpha()]
    clean_reviews.append(s)

In [6]:
len(clean_reviews)

147

In [7]:
clean_reviews

[['generat',
  'san',
  'franciscan',
  'even',
  'though',
  'member',
  'famili',
  'also',
  'own',
  'restaur',
  'pier',
  'favorit'],
 ['jeff',
  'owner',
  'j',
  'carrillo',
  'plumb',
  'run',
  'honest',
  'fair',
  'famili',
  'own',
  'busi',
  'trust',
  'get',
  'job',
  'done',
  'right',
  'high',
  'recommend',
  'servic'],
 ['thank',
  'plumb',
  'hero',
  'victor',
  'come',
  'provid',
  'servic',
  'fix',
  'home',
  'main',
  'water',
  'pipe',
  'plumb',
  'hero',
  'assess',
  'issu',
  'time',
  'manner',
  'clear',
  'work',
  'need',
  'done',
  'short',
  'cut',
  'taken',
  'plumb',
  'hero',
  'also',
  'generous',
  'quot',
  'provid',
  'anyon',
  'experi',
  'main',
  'water',
  'pipe',
  'issu',
  'etc',
  'reach',
  'plumb',
  'hero',
  'avail'],
 ['high',
  'recommend',
  'let',
  'dog',
  'lauren',
  'team',
  'absolut',
  'wonder',
  'profession',
  'client',
  'dog',
  'love',
  'dog',
  'pack',
  'much',
  'fun',
  'dog',
  'park',
  'also',
  't

In [8]:
unique_words = set([word for review in clean_reviews for word in review])

In [10]:
len(unique_words)

1444

In [17]:
nwz = np.random.rand(5, 3)

In [19]:
pwz = nwz/nwz.sum(axis=0,keepdims=1)

In [20]:
pwz

array([[0.27848297, 0.00237072, 0.09467207],
       [0.0398961 , 0.11492877, 0.01949206],
       [0.26152606, 0.15779091, 0.16567802],
       [0.32691769, 0.4539953 , 0.44694814],
       [0.09317718, 0.2709143 , 0.27320972]])

In [21]:
nzd = np.random.rand(3, 2)
pzd = nzd/nzd.sum(axis=0,keepdims=1)

In [23]:
pzd

array([[0.41840696, 0.32679751],
       [0.38544574, 0.28555209],
       [0.1961473 , 0.38765041]])

In [34]:
0.00237072*0.38544574

0.0009137839247328

In [49]:
pzwd = np.zeros((3, 5, 2))

In [50]:
pzwd

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
pzwd.shape

(3, 5, 2)

In [52]:
pwd = np.matmul(pwz, pzd)

In [53]:
pwd

array([[0.13600267, 0.12838417],
       [0.06481492, 0.0534122 ],
       [0.20274145, 0.19474874],
       [0.39944286, 0.40973482],
       [0.19699809, 0.21372007]])

In [54]:
pwd.shape

(5, 2)

In [55]:
for j in range(5):
    print (j)
    for k in range(2):
        print (k)
        pzwd[:,j,k] = np.multiply(pwz[j,:], pzd[:,k]) / pwd[j,k]

0
0
1
1
0
1
2
0
1
3
0
1
4
0
1


In [58]:
np.sum(pzwd[:,0,0])

1.0

In [59]:
np.sum(pzwd, axis=0)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
pzwd

array([[[0.85674211, 0.70886886],
        [0.25754571, 0.24410051],
        [0.53972348, 0.43885298],
        [0.34243856, 0.26074398],
        [0.19790029, 0.14247641]],

       [[0.00671887, 0.00527296],
        [0.6834661 , 0.61443169],
        [0.29998717, 0.23136234],
        [0.43808657, 0.31639807],
        [0.53006992, 0.36196948]],

       [[0.13653902, 0.28585818],
        [0.0589882 , 0.14146779],
        [0.16028935, 0.32978468],
        [0.21947487, 0.42285795],
        [0.27202979, 0.49555411]]])

In [73]:
ndw

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.]])

In [74]:
ndw.shape

(147, 1444)

In [75]:
pzwd.shape

(3, 5, 2)